# Generated by Django 5.1.4 on 2026-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_building_no_order_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery'), ('on_spot', 'On-the-spot Payment')], default='', max_length=20),
        ),
    ]
